---

- name: Install ceph-rest-api
  include_role: name=ceph_rest_api

- name: Install MongoDB
  include_role: name=mongodb

- name: Add Inkscope DB user
  mongodb_user:
    database: inkscope
    name: inkscope
    password: inkscope
    roles: dbOwner
    login_user: admin
    login_password: adminpass
    login_database: admin

- name: Install inkscope-common
  become: true
  apt:
    deb: /home/vagrant/inkscope-packaging/DEBS/inkscope-common_1.4.0.2.deb

- name: Generate inkscope.conf
  become: true
  template:
    src: inkscope.conf.j2
    dest: /opt/inkscope/etc/inkscope.conf

- name: Fetch inkscope.conf to copy it on all nodes later
  fetch:
    src: /opt/inkscope/etc/inkscope.conf
    dest: /tmp/
    flat: yes

- name: Install inkscope-cephprobe
  become: true
  apt:
    deb: /home/vagrant/inkscope-packaging/DEBS/inkscope-cephprobe_1.4.0.2.deb

- name: Start cephprobe
  become: true
  service:
    name: cephprobe
    state: started

- name: Install inkscope-admviz
  include_role: name=inkscope_admviz
