
  - name: Add MongoDB repository
    become: true
    lineinfile:
      line: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse
      path: /etc/apt/sources.list.d/mongodb-org-3.6.list
      create: yes

  - name: Install mongodb
    become: true
    apt:
      name:
        - mongodb-org
        - python-pymongo
      update_cache: yes
      allow_unauthenticated: yes

  - name: Configure MongoDB
    become: true
    template:
      dest: /etc/mongod.conf
      src: mongod.conf.j2
    register: mongodb_configured

  - name: Restart MongoDB
    become: true
    service:
      name: mongod
      state: restarted
    when: mongodb_configured.changed

  - name: Create MongoDB admin user
    mongodb_user:
      database: admin
      name: admin
      password: adminpass
      roles: userAdminAnyDatabase
    when: mongodb_configured.changed
