---

- name: Common initial steps
  hosts: all
  tasks:

  - name: Configure SSH on all node
    include_role: name=prepare_ssh

  - name: Get the package facts
    package_facts:
      manager: "apt"

- name: Initialize the Ceph cluster
  hosts: admin
  roles:
  - ceph_init

- name: Create OSDs
  hosts: data
  roles:
  - ceph_osds

- name: Install Inkscope
  hosts: admin
  tasks:

  - name: Download Inkscope
    git:
      dest: /home/vagrant/inkscope-packaging
      repo: https://github.com/inkscope/inkscope-packaging.git
      version: V1.4.0-2

  - name: Install ceph-rest-api
    include_role: name=ceph_rest_api

  - name: Install MongoDB
    include_role: name=mongodb

  - name: Add Inkscope DB user
    mongodb_user:
      database: inkscope
      name: inkscope
      password: inkscope
      roles: dbOwner
      login_user: admin
      login_password: adminpass
      login_database: admin
